//package ar.edu.unq.desapp.grupoj.desapp.model;
//
//import ar.edu.unq.desapp.grupoj.desapp.factories.UserFactory;
//import ar.edu.unq.desapp.grupoj.desapp.model.entities.Offer;
//import ar.edu.unq.desapp.grupoj.desapp.model.entities.User;
//import org.junit.jupiter.api.Test;
//
//import static org.junit.jupiter.api.Assertions.*;
//
//public class OfferTest {
//
//    @Test
//    public void offerConstructorIsAutoGenerated() {
//
//        Integer offerId = 1;
//        Double amount = 32d;
//        Double price = 42d;
//
//        String userName =  "Any user name";
//        User user = UserFactory.anyUserWithName(userName);
//
//        Offer offer = new Offer();
//
//        assertEquals(offer.getOfferId(), offerId);
//        assertEquals(offer.getAmount(), amount);
//        assertEquals(offer.getPrice(), price);
//        assertTrue(offer.getUser().contains(userName));
//
//    }
//}
