package ar.edu.unq.desapp.grupoj.desapp.model;

import ar.edu.unq.desapp.grupoj.desapp.factories.UserFactory;

import ar.edu.unq.desapp.grupoj.desapp.model.entities.User;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class UserTest {

    private Validator validator;

    @BeforeAll
    public void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    public void userConstructorIsAutoGenerated() {
        Integer userId = 1;
        String name = "UserName";
        String surname = "AValidSurname";
        String password = "aValidPAss!";
        String email = "validemail@hotmail.com";
        String address = "AValidAddress";
        String cvu = "1234567891234567891234";
        String cryptoWallet = "12345678";
        Integer operationAmount = 4;
        Integer score = 2;


        User user = UserFactory.createUser(userId, name, surname, password, email, address, cvu, cryptoWallet, operationAmount, score);


        assertIsValidUser(user);
        assertEquals(user.getUserId(), userId);
        assertEquals(user.getName(), name);
        assertEquals(user.getSurname(), surname);
        assertEquals(user.getPassword(), password);
        assertEquals(user.getEmail(), email);
        assertEquals(user.getAddress(), address);
        assertEquals(user.getCvu(), cvu);
        assertEquals(user.getCryptoWallet(), cryptoWallet);
        assertEquals(user.getOperationAmount(), operationAmount);
        assertEquals(user.getScore(), score);
    }

    @Test
    public void anUserHaveAnId() {
        Integer id = 1;
        User user = UserFactory.anyUserWithId(id);

        assertEquals(user.getUserId(), id);
    }

    @Test
    public void anUserCantHaveANameWithLessThan3Characters() {
        String expectedErrorMessage = "The name must have a minimum of 3 and a maximum of 30 characters";
        String invalidName = "I";
        User invalidUser = UserFactory.anyUserWithName(invalidName);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveANameWithMoreThan30Characters() {
        String expectedErrorMessage = "The name must have a minimum of 3 and a maximum of 30 characters";
        String invalidName = "ThisNameHaveMoreThanThirtyCharacters";
        User invalidUser = UserFactory.anyUserWithName(invalidName);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithAValidName() {
        String validName = "ValidName";
        User user = UserFactory.anyUserWithName(validName);

        assertIsValidUser(user);
        assertEquals(user.getName(), validName);
    }

    @Test
    public void anUserCantHaveASurnameWithLessThan3Characters() {
        String expectedErrorMessage = "The surname must have a minimum of 3 and a maximum of 30 characters";
        String invalidSurname = "I";
        User invalidUser = UserFactory.anyUserWithSurname(invalidSurname);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveASurnameWithMoreThan30Characters() {
        String expectedErrorMessage = "The surname must have a minimum of 3 and a maximum of 30 characters";
        String invalidSurname = "ThisSurnameHaveMoreThanThirtyCharacters";
        User invalidUser = UserFactory.anyUserWithSurname(invalidSurname);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithAValidSurname() {
        String validSurname = "ValidSurname";
        User user = UserFactory.anyUserWithSurname(validSurname);

        assertIsValidUser(user);
        assertEquals(user.getSurname(), validSurname);
    }

    @Test
    public void anUserCantHaveAPasswordWithLessThan6Characters() {
        String expectedErrorMessage = "Password must contain at least 1 lowercase, 1 uppercase, 1 special character and a minimum of 6 characters";
        String invalidPassword = "I";
        User invalidUser = UserFactory.anyUserWithPassword(invalidPassword);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveAPasswordWithoutASpecialCharacter() {
        String expectedErrorMessage = "Password must contain at least 1 lowercase, 1 uppercase, 1 special character and a minimum of 6 characters";
        String invalidPassword = "WithoutASpecialCharacter";
        User invalidUser = UserFactory.anyUserWithPassword(invalidPassword);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveAPasswordWithoutALowerCase() {
        String expectedErrorMessage = "Password must contain at least 1 lowercase, 1 uppercase, 1 special character and a minimum of 6 characters";
        String invalidPassword = "WITHOUTALOWERCASE!!!";
        User invalidUser = UserFactory.anyUserWithPassword(invalidPassword);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveAPasswordWithoutACapitalLetter() {
        String expectedErrorMessage = "Password must contain at least 1 lowercase, 1 uppercase, 1 special character and a minimum of 6 characters";
        String invalidPassword = "withoutascapitalletter!!!";
        User invalidUser = UserFactory.anyUserWithPassword(invalidPassword);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithAValidPassword() {
        String validPassword = "ValidPassword!";
        User user = UserFactory.anyUserWithPassword(validPassword);

        assertIsValidUser(user);
        assertEquals(user.getPassword(), validPassword);
    }

    @Test
    public void anUserCantHaveAEmailWithoutEmailFormat() {
        String expectedErrorMessage = "Invalid email";
        String invalidEmail = "invalidemail!!!";
        User invalidUser = UserFactory.anyUserWithEmail(invalidEmail);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithValidEmailFormat() {
        String validEmail = "validemail@hotmail.com";
        User user = UserFactory.anyUserWithEmail(validEmail);

        assertIsValidUser(user);
        assertEquals(user.getEmail(), validEmail);
    }

    @Test
    public void anUserCantHaveAAddressWithLessThan10Characters() {
        String expectedErrorMessage = "The address must have a minimum of 10 and a maximum of 30 characters";
        String invalidAddress = "NineChars";
        User invalidUser = UserFactory.anyUserWithAddress(invalidAddress);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveAnAddressWithMoreThan30Characters() {
        String expectedErrorMessage = "The address must have a minimum of 10 and a maximum of 30 characters";
        String invalidName = "ThisNameHaveMoreThanThirtyCharacters";
        User invalidUser = UserFactory.anyUserWithAddress(invalidName);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithAValidAddress() {
        String validAddress = "ValidAddress";
        User user = UserFactory.anyUserWithAddress(validAddress);

        assertIsValidUser(user);
        assertEquals(user.getAddress(), validAddress);
    }

    @Test
    public void anUserCantHaveACVUWithLessThan22Digits() {
        String expectedErrorMessage = "Mercado Pago CVU length must be of 22 digits";
        String invalidCVU = "123213";
        User invalidUser = UserFactory.anyUserWithCVU(invalidCVU);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveACVUWithMoreThan22Digits() {
        String expectedErrorMessage = "Mercado Pago CVU length must be of 22 digits";
        String invalidCVU = "12345678912345678912345";
        User invalidUser = UserFactory.anyUserWithCVU(invalidCVU);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithAValidCVU() {
        String validCVU = "1234567891234567891234";
        User user = UserFactory.anyUserWithCVU(validCVU);

        assertIsValidUser(user);
        assertEquals(user.getCvu(), validCVU);
    }

    @Test
    public void anUserCantHaveACryptoWalletWithLessThan8Digits() {
        String expectedErrorMessage = "Crypto Wallet Address length must be of 8 digits";
        String invalidCryptoWallet = "1234567";
        User invalidUser = UserFactory.anyUserWithCryptoWallet(invalidCryptoWallet);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void anUserCantHaveACryptoWalletWithMoreThan9Digits() {
        String expectedErrorMessage = "Crypto Wallet Address length must be of 8 digits";
        String invalidCryptoWallet = "123456789";
        User invalidUser = UserFactory.anyUserWithCryptoWallet(invalidCryptoWallet);

        assertIsNotValidUserWith(expectedErrorMessage, invalidUser);
    }

    @Test
    public void whenCreateAUserWithAValidCryptoWallet() {
        String validCryptoWallet = "12345678";
        User user = UserFactory.anyUserWithCryptoWallet(validCryptoWallet);

        assertIsValidUser(user);
        assertEquals(user.getCryptoWallet(), validCryptoWallet);
    }

    @Test
    public void whenTheUserHadNoOperations_theUserReputationIs0() {
        Double expectedUserReputation = 0.0;
        User user = UserFactory.anyUserWithOperationsAmountAndScore(0,0);

        assertEquals(expectedUserReputation, user.getReputation());
    }

    @Test
    public void theUserReputationIsTheDivisionOfTheScoreAndTheAmountOfOperations() {
        Integer operationsAmount = 2;
        Integer score = 4;
        Double expectedUserReputation = (double) (score / operationsAmount);
        User user = UserFactory.anyUserWithOperationsAmountAndScore(operationsAmount, score);

        assertEquals(expectedUserReputation, user.getReputation());
    }

    private void assertIsNotValidUserWith(String expectedErrorMessage, User user) {
        Set<ConstraintViolation<User>> violations = validator.validate(user);

        String errorMessage = "";
        for (ConstraintViolation<User> violation : violations) {
            errorMessage += violation.getMessage();
        }
        assertEquals(expectedErrorMessage, errorMessage);
    }

    private void assertIsValidUser(User user) {
        Set<ConstraintViolation<User>> violations = validator.validate(user);

        assertTrue(violations.isEmpty());
    }
}